[package]
name = "mirudi"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
